"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Luke Guequierre, this 
programming assignment is my own work and I have not provided this code to 
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: lkg746
"""


def length_of_longest_substring_n3(s):
    """
    Finds the length of the longest substring without repeating characters
    using a brute force approach (O(N^3)).

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        for l in range(i, len(s)):
            unique = True
            freq_list = []
            for n in range(256):
                freq_list.append(0)
            substr = s[i:l+1]
            for c in substr:
                freq_list[ord(c)] += 1
            for n in freq_list:
                if n > 1:
                    unique = False
            if len(substr) > max_length and unique:
                max_length = len(substr)
    return max_length


def length_of_longest_substring_n2(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N^2)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        freq_list = []
        for n in range(256):
            freq_list.append(0)
        for l in range(i, len(s)):
            unique = True
            freq_list[ord(s[l])] += 1
            for n in freq_list:
                if n > 1:
                    unique = False
            if unique:
                max_length = max(max_length, l + 1 - i)
    return max_length


def length_of_longest_substring_n(s):
    """
    Finds the length of the longest substring without repeating characters
    using a frequency list approach (O(N)), converting each character to
    their corresponding numeric representation in ASCII as the index into the
    frequency list. However, this approach stops early, breaking out of the inner
    loop when a repeating character is found. You may also choose to challenge
    yourself by implementing a sliding window approach.

    pre: s is a string of arbitrary length, possibly empty.
    post: Returns an integer >= 0 representing the length of the longest substring
          in s that contains no repeating characters.
    """
    max_length = 0
    for i in range(len(s)):
        unique = True
        freq_list = []
        n = 0
        while n < 256:
            freq_list.append(0)
            n += 1
        l = i
        while l < len(s) and unique:
            freq_list[ord(s[l])] += 1
            if freq_list[ord(s[l])] > 1:
                unique = False
            if (l+1) - i > max_length and unique:
                max_length = (l+1) - i
            l += 1
    return max_length
