"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Luke Guequierre, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: lkg746
"""


def group_sum(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_sum(start + 1, nums, target - nums[start]):
        return True
    return group_sum(start + 1, nums, target)


def group_sum_6(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to the
    given target. Additionally, if there is are 6's present in the array, they must all
    be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_sum_6(start + 1, nums, target - nums[start]):
        return True
    if nums[start] != 6:
        return group_sum_6(start + 1, nums, target)
    return False


def group_no_adj(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a value is chosen, the value immediately after
    (the value adjacent) cannot be chosen.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_no_adj(start + 2, nums, target - nums[start]):
        return True
    return group_no_adj(start + 1, nums, target)



def group_sum_5(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if a multiple of 5 is in the array, it must be included
    If the value immediately following a multiple of 5 if 1, it must not be chosen

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if start > 0:
        if nums[start-1] // 5 == 0 and nums[start] == 1:
            if group_sum_5(start + 2, nums, target - nums[start]):
                return  True
    if group_sum_5(start + 1, nums, target - nums[start]):
        return  True
    if nums[start] % 5 != 0:
        return group_sum_5(start + 1, nums, target)
    return False


def group_sum_clump(start, nums, target):
    """
    Given a list of ints, determine if there exists a group of some ints that sum to
    the given target. Additionally, if there is a group of identical numbers in succession,
    they must all be chosen, or none of them must be chosen.
    EX: [1, 2, 2, 2, 5, 2], all three of the middle 2's must be chosen, or none of them must be
    chosen to be included in the sum. One loop is allowed to check for identical numbers.

    pre: start >= 0, len(nums) >= 0, target >= 0, nums will only contain ints
    post: return True if nums has a group of ints that sum to target, False otherwise
    """
    if start >= len(nums):
        return target == 0
    if group_sum_clump(start + 1, nums, target - nums[start]):
        return True
    if start+1 < len(nums) and start-1 >= 0:
        if nums[start+1] != nums[start] and nums[start-1] != nums[start]:
            return group_sum_clump(start + 1, nums, target)
        return False
    return group_sum_clump(start + 1, nums, target)


def split_array(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    combinations = []
    return split_array_helper(combinations, 0, nums)


def split_array_helper(combos, start, nums):
    """
    Recursive helper for split array function
    """
    if start >= len(nums):
        if len(combos) >= 2:
            return sum(combos[0]) == sum(combos[1])
        else:
            return nums == []
    combos.append(nums[:start])
    combos.append(nums[start:])
    if len(combos) >= 2:
        if sum(combos[0]) == sum(combos[1]):
            return True
    combos = []
    return split_array_helper(combos, start + 1, nums)


def split_odd_10(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of one group must be odd, while the other group must be a multiple of 10
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    combinations = []
    return split_odd_10_helper(combinations, 0, nums)


def split_odd_10_helper(combos, start, nums):
    """
    Recursive helper for split odd 10 function
    """
    if start >= len(nums):
        if len(combos) >= 2:
            if sum(combos[0]) % 2 != 0:
                return sum(combos[1]) % 10 == 0
            if sum(combos[1]) % 2 != 0:
                return sum(combos[0]) % 10 == 0
            return False
        return False
    combos.append(nums[:start])
    combos.append(nums[start:])
    if len(combos) >= 2:
        if sum(combos[0]) % 2 != 0:
            if sum(combos[1]) % 10 == 0:
                return True
        if sum(combos[1]) % 2 != 0:
            if sum(combos[0]) % 10 == 0:
                return True
    combos = []
    return split_odd_10_helper(combos, start + 1, nums)



# TODO: Modify this function. You may delete this comment when you are done.
def split_53(nums):
    """
    Given a list of ints, determine if the numbers can be split evenly into two groups
    The sum of these two groups must be equal
    Additionally, all multiples of 5 must be in one group, and all multiples of 3 (and not 5)
    must be in the other group
    Write a recursive helper to call from this function

    pre: len(nums) >= 0, nums will only contain ints
    post: return True if nums can be split, False otherwise
    """
    combinations = []
    return split_53_helper(combinations, 0, nums)


def split_53_helper(combos, start, nums):
    """
    Recursive helper for split 53 array function
    """
    if start >= len(nums):
        if len(combos) >= 2:
            if sum(combos[1]) == sum(combos[0]):
                list_5 = False
                list_3 = False
                index = 0
                while index < len(combos[0]):
                    if combos[0][index] % 5 == 0:
                        list_5 = True
                        for num in combos[1]:
                            if num % 5 == 0:
                                return False
                        if list_3:
                            return False
                    if combos[0][index] % 3 == 0:
                        list_3 = True
                        for num in combos[1]:
                            if num % 3 == 0:
                                return False
                        if list_5:
                            return False
                    index += 1
                list_5 = False
                list_3 = False
                index = 0
                while index < len(combos[1]):
                    if combos[1][index] % 5 == 0:
                        list_5 = True
                        for num in combos[0]:
                            if num % 5 == 0:
                                return False
                        if list_3:
                            return False
                    if combos[1][index] % 3 == 0:
                        list_3 = True
                        for num in combos[0]:
                            if num % 3 == 0:
                                return False
                        if list_5:
                            return False
                    index += 1
                return True
        return False
    combos.append(nums[:start])
    combos.append(nums[start:])
    #print(start, combos, end=" | ")
    if len(combos) >= 2:
        if sum(combos[1]) == sum(combos[0]):
            list_5 = False
            list_3 = False
            good_list = True
            index = 0
            while good_list and index < len(combos[0]):
                if combos[0][index] % 5 == 0:
                    list_5 = True
                    for num in combos[1]:
                        if num % 5 == 0:
                            good_list = False
                    if list_3:
                        good_list = False
                if combos[0][index] % 3 == 0:
                    list_3 = True
                    for num in combos[1]:
                        if num % 3 == 0:
                            good_list = False
                    if list_5:
                        good_list = False
                index += 1
            list_5 = False
            list_3 = False
            good_list = True
            index = 0
            while good_list and index < len(combos[1]):
                if combos[1][index] % 5 == 0:
                    list_5 = True
                    for num in combos[0]:
                        if num % 5 == 0:
                            good_list = False
                    if list_3:
                        good_list = False
                if combos[1][index] % 3 == 0:
                    list_3 = True
                    for num in combos[0]:
                        if num % 3 == 0:
                            good_list = False
                    if list_5:
                        good_list = False
                index += 1
            if good_list:
                return True
    combos = []
    return split_53_helper(combos, start + 1, nums)

#nums = [2, 4, 2]
#print(split_53(nums))