"""
Student information for this assignment:

Replace <FULL NAME> with your name.
On my honor, Luke Guequierre, this
programming assignment is my own work and I have not provided this code to
any other student.

I have read and understand the course syllabus's guidelines regarding Academic
Integrity. I understand that if I violate the Academic Integrity policy (e.g.
copy code from someone else, have the code generated by an LLM, or give my
code to someone else), the case shall be submitted to the Office of the Dean of
Students. Academic penalties up to and including an F in the course are likely.

UT EID 1: lkg746
"""

# the constant used to calculate the step size
STEP_SIZE_CONSTANT = 3


# DO NOT modify this function.
def is_prime(n):
    """
    Determines if a number is prime.

    pre: n is a positive integer.
    post: Returns True if n is prime, otherwise returns False.
    """
    if n == 1:
        return False

    limit = int(n**0.5) + 1
    div = 2
    while div < limit:
        if n % div == 0:
            return False
        div += 1
    return True


# DO NOT modify this function.
def hash_word(s, size):
    """
    Hashes a lowercase string to an index in a hash table.

    pre: s is a lowercase string, and size is a positive integer representing either
         hash table size or the constant for double hashing.
    post: Returns an integer index in the range [0, size - 1] where the string hashes to.
    """
    hash_idx = 0
    for c in s:
        letter = ord(c) - 96
        hash_idx = (hash_idx * 26 + letter) % size
    return hash_idx


def step_size(s):
    """
    Calculates step size for double hashing using STEP_SIZE_CONSTANT.

    pre: s is a lowercase string.
    post: Returns the calculated step size as an integer based on the provided string.
    """
    stepsize = 0
    for c in s:
        letter = ord(c) - 96
        stepsize = (stepsize * 26 + letter) % STEP_SIZE_CONSTANT
    return STEP_SIZE_CONSTANT - stepsize


def insert_word(s, hash_table):
    """
    Inserts a string into the hash table using double hashing for collision resolution.
    No duplicates are allowed.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Inserts s into hash_table at the correct index; resolves any collisions
          by double hashing.
    """
    size = len(hash_table)
    index = hash_word(s, size)
    if hash_table[index] == s:
        return
    stepsize = step_size(s)
    count = 0
    while hash_table[index] != '' and count < size:
        if index + stepsize < size:
            index += stepsize
        else:
            index = (index + stepsize) - size
        count += 1
        if hash_table[index] == s:
            return
    hash_table[index] = s


def find_word(s, hash_table):
    """
    Searches for a string in the hash table.
    Note: using the `in` operator is incorrect as that will be O(N). We want
          an O(1) time average time complexity using hashing.

    pre: s is a string, and hash_table is a list representing the hash table.
    post: Returns True if s is found in hash_table, otherwise returns False.
    """
    size = len(hash_table)
    index = hash_word(s, size)
    if hash_table[index] == s:
        return True
    stepsize = step_size(s)
    count = 0
    while hash_table[index] != '' and count < size:
        if index + stepsize < size:
            index += stepsize
        else:
            index = (index + stepsize) - size
        count += 1
        if hash_table[index] == s:
            return True
    return False


def is_reducible(s, hash_table, hash_memo):
    """
    Determines if a string is reducible using a recursive check.

    pre: s is a lowercase string, hash_table is a list representing the hash table,
         and hash_memo is a list representing the hash table
         for memoization.
    post: Returns True if s is reducible (also updates hash_memo by
          inserting s if reducible), otherwise returns False.
    """
    return reductible_helper(s, hash_table, hash_memo, 0, len(s))

def reductible_helper(s, hash_table, hash_memo, l, r):
    """
    Recursive helper for is_reducible
    """
    if find_word(s, hash_memo):
        return True
    if l + 1 == r:
        if s[l:r].lower() == 'a' or s[l:r].lower() == 'i' or s[l:r].lower() == 'o':
            return True
        return False
    if find_word(s[l:r], hash_table):
        if reductible_helper(s, hash_table, hash_memo, l + 1, r):
            insert_word(s[l:r], hash_memo)
            return True
        if reductible_helper(s, hash_table, hash_memo, l, r - 1):
            insert_word(s[l:r], hash_memo)
            return True
        return False
    return False



def get_longest_words(string_list):
    """
    Finds longest words from a list.

    pre: string_list is a list of lowercase strings.
    post: Returns a list of words in string_list that have the maximum length.
    """
    if string_list == []:
        return []
    words_len = {}
    biggest = 0
    for word in string_list:
        size = len(word)
        if size not in words_len:
            words_len[size] = [word]
        else:
            words_len[size].append(word)
        biggest = max(biggest, size)
    return words_len[biggest]


def main():
    """The main function that calculates the longest reducible words"""
    # create an empty word_list
    word_list = []
    # read words using input redirection
    # where each line read from input()
    # should be a single word. Append to word_list
    # ensure each word has no trailing white space.
    word = input().strip()
    while word != '':
        word_list.append(word)
        try:
            word = input().strip()
        except EOFError:
            word = ''
    # find length of word_list
    wl_length = len(word_list)
    # determine prime number N that is greater than twice
    # the length of the word_list
    n = wl_length * 2
    while not is_prime(n):
        if n % 2 == 0:
            n += 1
        else:
            n += 2
    # create an empty hash_list
    hash_list = ['']
    # populate the hash_list with N blank strings
    hash_list *= n
    # hash each word in word_list into hash_list
    # for collisions use double hashing
    for word in word_list:
        print('new word: ' + word)
        insert_word(word, hash_list)
    # create an empty hash_memo of size M
    # we do not know a priori how many words will be reducible
    # let us assume it is 10 percent (fairly safe) of the words
    # then M is a prime number that is slightly greater than
    # 0.2 * size of word_list
    m = int(0.2 * n)
    while not is_prime(m):
        if m % 2 == 0:
            m += 1
        else:
            m += 2
    # populate the hash_memo with M blank strings
    hash_memo = [''] * m
    # create an empty list reducible_words
    reducible_words = []
    # for each word in the word_list recursively determine
    # if it is reducible, if it is, add it to reducible_words
    # as you recursively remove one letter at a time check
    # first if the sub-word exists in the hash_memo. if it does
    # then the word is reducible and you do not have to test
    # any further. add the word to the hash_memo.
    for word in word_list:
        if is_reducible(word, hash_list, hash_memo):
            reducible_words.append(word)
    # find the largest reducible words in reducible_words
    longest = get_longest_words(reducible_words)
    # print the reducible words in alphabetical order
    # one word per line
    longest = longest.sort()
    for word in longest:
        print(word)


if __name__ == "__main__":
    main()
